import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "無限ブログ",
  description: "A blog generated by Gemini",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white text-gray-800 dark:bg-gray-900 dark:text-gray-100`}>
        <header className="bg-gray-800 text-white p-4 dark:bg-gray-950">
          <Link href="/" className="text-2xl font-bold text-white no-underline">
            <h1>無限ブログ</h1>
          </Link>
        </header>
        <main className="container mx-auto p-4 min-h-screen">{children}</main>
        <footer className="bg-gray-800 text-white p-4 text-center dark:bg-gray-950">
          <p>&copy; 2025 無限ブログ</p>
        </footer>
      </body>
    </html>
  );
}
