import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Link from 'next/link';
import { getSortedPostsData } from '@/lib/posts';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "無限ブログ",
  description: "A blog generated by Gemini",
  icons: {
    icon: '/favicon.svg',
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const allPostsData = getSortedPostsData(); // Fetch all posts data
  const tagCounts: { [key: string]: number } = {};

  allPostsData.forEach(post => {
    post.tags.forEach(tag => {
      tagCounts[tag] = (tagCounts[tag] || 0) + 1;
    });
  });

  const sortedTags = Object.entries(tagCounts).sort(([, countA], [, countB]) => countB - countA);
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white text-gray-800 dark:bg-gray-900 dark:text-gray-100`}>
        <header className="bg-gray-800 text-white p-4 dark:bg-gray-950">
          <Link href="/" className="text-2xl font-bold text-white no-underline">
            <h1>無限ブログ</h1>
          </Link>
        </header>
        <main className="container mx-auto p-4 min-h-screen md:flex">
          <div className="w-full md:w-3/4 md:pr-4">{children}</div>
          <div className="w-full md:w-1/4 md:pl-4 md:border-l md:border-gray-200 dark:md:border-gray-700 mt-8 md:mt-0 md:pt-0 pt-4 border-t md:border-t-0 border-gray-200 dark:border-gray-700">
            <h2 className="text-xl font-bold mb-4">タグ</h2>
            <ul>
              {sortedTags.map(([tag, count]) => (
                <li key={tag} className="mb-2">
                  <Link href={`/tags/${encodeURIComponent(tag)}`} className="text-teal-600 hover:underline dark:text-teal-400">
                    {tag} ({count})
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </main>
        <footer className="bg-gray-800 text-white p-4 text-center dark:bg-gray-950">
          <p>&copy; 2025 無限ブログ</p>
        </footer>
        <Script async src="https://www.googletagmanager.com/gtag/js?id=G-254J6XGXSP" strategy="afterInteractive" />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-254J6XGXSP');
          `}
        </Script>
      </body>
    </html>
  );
}
